RemoteCacheKick upgrade to Sitecore 9.3 - Initial commit of upgrading .net framework to 4.8 according to https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB0087164 + fixed initial compile issue of:
Severity Code Description Project File Line Suppression State
Error CS1617 Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6. Community.Foundation.RemoteCacheKick C:\Projects\Community.Foundation.RemoteCacheKick\src\Foundation\RemoteCacheKick\code\CSC 1 Active